name: 'My First Github Actions'

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main: 

jobs:
  first_job:
    name: 'Build App'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        users: actions/checkout@v2
      
      - name: Setu .NET SDK
        users: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      
      - name: Restore NuGet packages
        shell: bash
        run: |
          dotnet restore ./api
      
      - name: Build App
        shell: bash
        run: |
          dotnet build ./api -c Release
      
      - name: Create artifact
        shell: bash
        run: |
          dotnet pushlish ./api -c Release -o ./api/bin/pushish

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: apiapp
          path: api/bin/pushlished