name: 'My First Github Actions'

on: push

jobs:
  first_job:
    name: 'First Job'

    strategy:
      matrix:
        os: ['windows-latest', 'macos-latest', 'ubuntu-latest']
        nodejs: [ '14.x', '16.x' ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Choose node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs }}

      - name: Say Hello World from ${{ matrix.os }}
        shell: bash
        run: |
          echo "Hello, from ${{ matrix.os }}"
          echo "node version: ${{ node --version }}"