name: 'My First Github Actions'

on: [ 'push', 'pull_request' ]

jobs:
  first_job:
    name: 'First Job'
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello from first Job
        sehll: bash
        run: |
          echo "Hello World"

  second_job:
      name: 'Second Job'
      needs: first_job
      runs-on: ubuntu-latest

      steps:
        - name: Say Hello from second Job
          sehll: bash
          run: |
            echo "Hello World 2"
