name: 'My First Github Actions'

on: push

jobs:
  first_job:
    name: 'First Job'
    runs-on: ubuntu-latest

    steps:
      - name: Mask output value
        shell: bash
        id: first
        run: |
          value1='This is super secret value'

          echo "::add-mask::$value1"
          echo "::set-output name=first_value::$value1"

      - name: Check output value
        shell: bash
        run: |
          echo "value: ${{ steps.first.outputs.first_value }}"