name: 'My First Github Actions'

on: [ 'push', 'pull_request' ]

jobs:
  first_job:
    name: 'First Job'
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello from first Job
        shell: bash
        run: |
          echo "Hello World"

  second_job:
      name: 'Second Job'
      runs-on: ubuntu-latest

      steps:
        - name: Say Hello from second Job
          shell: bash
          run: |
            echo "Hello World 2"
  
  third_job:
    name: 'third Job'
    needs:
      - first_job
      - second_job
    
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello from third Job
        shell: bash
        run: |
          echo "Hello World 3"
